/**
 * Fix #2: AI Quality Baseline Verification
 * Verifies the baseline JSON generated by run-baseline.ts (600 prompts).
 * The baseline runner is executed separately to avoid Jest timeout issues.
 */
import * as fs from 'fs';
import * as path from 'path';

const baselinePath = path.join(__dirname, '../../docs/phase-2/ai-quality-baseline.json');

describe('T-P2-FIX2: AI Quality Baseline Verification', () => {
  let data: any;

  beforeAll(() => {
    expect(fs.existsSync(baselinePath)).toBe(true);
    data = JSON.parse(fs.readFileSync(baselinePath, 'utf-8'));
  });

  it('should have 600 total records', () => {
    expect(data.records.length).toBe(600);
  });

  it('should have 100 records per interface', () => {
    const interfaces = ['text_generation', 'classification', 'summarization', 'vision_analysis', 'speech_synthesis', 'embedding'];
    for (const iface of interfaces) {
      const count = data.records.filter((r: any) => r.interface === iface).length;
      expect(count).toBe(100);
    }
  });

  it('should have >= 90% overall success rate', () => {
    const successRate = data.records.filter((r: any) => r.success).length / data.records.length;
    expect(successRate).toBeGreaterThanOrEqual(0.9);
  });

  it('should have ITextGeneration success rate >= 90%', () => {
    const iface = data.summary.by_interface.text_generation;
    expect(iface.success_rate).toBeGreaterThanOrEqual(0.9);
    expect(iface.total).toBe(100);
  });

  it('should have IClassification success rate >= 90%', () => {
    const iface = data.summary.by_interface.classification;
    expect(iface.success_rate).toBeGreaterThanOrEqual(0.9);
    expect(iface.total).toBe(100);
  });

  it('should have ISummarization success rate >= 90%', () => {
    const iface = data.summary.by_interface.summarization;
    expect(iface.success_rate).toBeGreaterThanOrEqual(0.9);
    expect(iface.total).toBe(100);
  });

  it('should have IVisionAnalysis success rate >= 90%', () => {
    const iface = data.summary.by_interface.vision_analysis;
    expect(iface.success_rate).toBeGreaterThanOrEqual(0.9);
    expect(iface.total).toBe(100);
  });

  it('should have ISpeechSynthesis success rate >= 90%', () => {
    const iface = data.summary.by_interface.speech_synthesis;
    expect(iface.success_rate).toBeGreaterThanOrEqual(0.9);
    expect(iface.total).toBe(100);
  });

  it('should have IEmbedding success rate >= 90%', () => {
    const iface = data.summary.by_interface.embedding;
    expect(iface.success_rate).toBeGreaterThanOrEqual(0.9);
    expect(iface.total).toBe(100);
  });

  it('should have reasonable latency for text generation (p95 < 5000ms)', () => {
    expect(data.summary.by_interface.text_generation.latency_p95).toBeLessThan(5000);
  });

  it('should have reasonable latency for classification (p95 < 5000ms)', () => {
    expect(data.summary.by_interface.classification.latency_p95).toBeLessThan(5000);
  });

  it('should have reasonable latency for embedding (p95 < 5000ms)', () => {
    expect(data.summary.by_interface.embedding.latency_p95).toBeLessThan(5000);
  });

  it('should have quality scores recorded', () => {
    for (const iface of Object.values(data.summary.by_interface) as any[]) {
      expect(iface.avg_quality).toBeGreaterThan(0);
    }
  });

  it('should have cost tracking recorded', () => {
    for (const iface of Object.values(data.summary.by_interface) as any[]) {
      expect(iface.total_cost).toBeGreaterThanOrEqual(0);
    }
  });

  it('should have model information in summary', () => {
    expect(data.summary.model).toBeDefined();
    expect(data.summary.generated_at).toBeDefined();
  });
});
